name: Job Hunter

on:
  workflow_dispatch: # Позволяет запускать вручную
  schedule:
    - cron: "0 * * * *" # Запуск каждый час (лучше не частить, чтобы не забанили)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Установка браузера Chromium и системных библиотек для него
          python -m playwright install chromium --with-deps

      - name: Run script
        env:
          # ОБЯЗАТЕЛЬНО: пробрасываем секреты в систему
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
